apiVersion: extensions/v1beta1  
kind: Ingress  
metadata:  
  name: test-ingress
  namespace: sandbox
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "test-ip"
#    kubernetes.io/ingress.allow-http: "false"
spec:  
  tls:
  - secretName: foo-secret 
  backend:
    serviceName: test-app
    servicePort: 8080
